#
# Manually move a specific servo to a specific position
#

# REQUEST -------------------------------------------------------------------------------------

# Servos
int32 HEAD_CENTER=0
int32 NECK_TOP=1
int32 NECK_BOTTOM=2
int32 EYE_RIGHT=3
int32 EYE_LEFT=4
int32 ARM_LEFT=5
int32 ARM_RIGHT=6

# Either name OR index should be used to specify the servo.
# if both are used, the service will error out

# Name of servo to select (lower case version of the enumeration above)
string name

# Index of servo to select (values of enumeration above)
int32 index -1

# Position to command servo to (percentage of full movement range, 0.0 to 1.0)
float64 position

---
# RESPONSE -------------------------------------------------------------------------------------

# Indicates whether command was queued successfully
bool success